services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      # - ./data:/data
      - ./data_test:/data
      - ./src/neo4j/csv:/import
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_transaction_total_max=4G
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G

  api:
    stdin_open: true
    tty: true
    # container_name: movie-api
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - ./src:/app/src  # For development hot-reload
    depends_on:
      - neo4j

